export const correctMessages = [
"Wah bhai 🔥",
"Concept pakad liya tune",
"Seedha +4 mil gaya",
"NEET me aaya to tera hi hai",
"Doctor material 😎",
"AIIMS calling ☎️",
"NCERT strong ho rahi hai",
"Khatarnak preparation chal rahi",
"Tu ruk rank aa rahi hai",
"Perfect attempt",
"Bhai ne system hila diya",
"Paper setter ro dega",
"Ek aur sahi kar ab",
"Flow state achieved ⚡",
"Dimag garam ho gaya tera",
"Ab tu rukne wala nahi",
"Sharp brain",
"Topper vibes",
"Bilkul textbook answer",
"Bahut badhiya",
"Confidence boost unlocked",
"Yahi consistency chahiye",
"Legend move",
"Mindset sahi hai tera"
]

export const wrongMessages = [
"Koi na bhai",
"Sabse common mistake yehi",
"NCERT line miss ho gayi",
"Isko mark kar revise me",
"Almost tha",
"Galti samajh gaya to +4 next",
"Yahi question exam me aata",
"Ab yaad rahega lifetime",
"Concept thoda hil gaya",
"Tension nahi lena",
"Next wala sahi karega",
"Ye trap question tha",
"Paper setter ka favourite trap",
"Revision required 📚",
"Dhyaan se padhna padega",
"Ek baar explanation dekh",
"Is topic pe weak hai tu abhi",
"Practice se aayega",
"Confidence loose mat kar",
"Learning ho rahi hai",
"Galti = improvement",
"Ab strong ho jayega topic"
]

export const streakMessages = [
"Hattt 🔥 streak chal rahi",
"Ab flow aa gaya",
"Momentum ban gaya",
"Mat ruk abhi",
"Rank mode ON ⚡",
"Tu garam ho gaya",
"Ab dimaag warm up ho gaya",
"Abhi paper dedo koi",
"3 sahi lagatar 😳",
"Machine ban gaya tu",
"Topper mode activated",
"Ab speed dangerous hai",
"Consistency king 👑"
]
